name: 'Release'
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}
    steps:
      - name: Print environment variables
        run: |
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_REF_TYPE=$GITHUB_REF_TYPE"
      - name: Is not a tag
        if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
        shell: bash
        run: exit 1
      - name: create release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const linkBase = `https://github.com/mega-manipulator/mega-manipulator-standalone/releases/download/${process.env.GITHUB_REF_NAME}/mega-manipulator_${process.env.GITHUB_REF_NAME.substring(1)}`;
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `${process.env.GITHUB_REF_NAME}`,
              name: `Desktop App ${process.env.GITHUB_REF_NAME}`,
              body: `Take a look at the assets to download and install this app.
            
            [Mac aarch64](${linkBase}_aarch64.dmg)
            [Mac x64](${linkBase}_x64.dmg)
            [Windows](${linkBase}_x64_en-US.msi)
            [Linux .deb](${linkBase}_amd64.deb)
            `
              draft: true,
              prerelease: false
            })
            return data.id
  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: mega-manipulator/tauri-setup-action@main
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: install app dependencies and build it
        run: yarn && yarn build
      - uses: tauri-apps/tauri-action@v0
        env:
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}

  publish-release:
    runs-on: ubuntu-20.04
    needs: [ create-release, build-tauri ]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
