name: 'Setup'
description: 'Setup Node, Rust, and Tauri'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - name: set npm version
      shell: bash
      if: ${{ env.GITHUB_REF_TYPE == tag }}
      run: npm version ${{ env.GITHUB_REF_NAME }}
    - name: set cargo version
      shell: bash
      if: ${{ env.GITHUB_REF_TYPE == tag }}
      working-directory: src-tauri
      env:
        RELEASE_TAG: ${{ env.GITHUB_REF_NAME }}
      run: |
        mv Cargo.toml Cargo.toml.orig
        sed "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.toml.orig >Cargo.toml
        mv Cargo.lock Cargo.lock.orig
        sed "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.lock.orig >Cargo.lock
