name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  test-tauri:
#    strategy:
#      fail-fast: true
#      matrix:
#        platform: [macos-latest, ubuntu-20.04, windows-latest]
#    runs-on: ${{ matrix.platform }}

    runs-on: ubuntu-latest

    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      #group: ${{ github.workflow }}-${{ matrix.platform }}-${{ github.head_ref || github.ref }}
    steps:
      - uses: mega-manipulator/tauri-setup-action@main
      - uses: tauri-apps/tauri-action@v0
        env:
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
