name: Update version
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  draft_version_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update the updater file version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: ./update_updater.bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: bump/updater-file-versions
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            tauri-update.json
          assignees: jensim
          reviewers: jensim
          title: Update versions in the updater file
          body: |
            # Update the versions

            When all looks good ofc.

            [ ] Does the application start?
            [ ] Open all menu pages
            [ ] Click around like a mad dog
